export const products=[
  {
    "name": "Phinix Damp Coat Exterior Primer",
    "raw_snippet": "Phinix  Damp Coat  Exterior  Primer, is made from high Quality pure   elstoplasty  emulsion. It can be used for all priming requirement for exterior  & interior walls.  to felling miner cracks & damp locking.  In this  primer  we will use some water proofing chemicals its help to stop miner leakages. After applying  damp  coat  primer then apply 2 coats  top  coat of  paint or premium  exterior paint  its give  better  result.",
    "area_of_application": "Plaster, Concrete , Asbestos sheets",
    "method_of_application": "can be applied by Brush, Roller, spray.",
    "thinning": "40% by  volume .",
    "coverage": "120/130 sq. ft. per  Litre per coat.",
    "packing_available": "1lit, 4lit, 10lit, 20litz",
    "images": "img/IMG-20250915-WA0020.jpg"
  },
  {
    "name": "Phinix Gold Exterior / Interior Primer ",
    "raw_snippet": "Phinix  Gold is made from acrylic co – polymer emulsion. It can be used for all priming requirement for exterior   & interior walls.",
    "area_of_application": "Plaster, Concrete ,Asbestos  Sheets",
    "method_of_application": "can be applied by Brush or Roller",
    "thinning": "50%  by volume.",
    "coverage": "100/110/ sq ft. per Litre per coat",
    "packing_available": "1lit, 4lit, 10lit, 20lit, ( Bags )",
    "images": "img/IMG-20250915-WA0027.jpg"
  },
  {
    "name": " Phinix Max Exterior / Interior Primer",
    "raw_snippet": "Phinix   Max  Exterior  /interior Primer, is made  from  acrylic copolymer emulsion. It can be used for all priming requirements for exterior & interior walls. 1.    Diamond  Coat  Luxury Emulsion Diamond Coat Luxury Emulsion is a premium emulsion  paint made of quality pure acrylic polymers  that providers a luxurious finish & silky appearance to your  walls.a)  Low VOC & odourless  - 5 Years performance  .b)  Good wash ability   - Anti bacterial ",
    "area_of_application": "Plaster, Fall ceilings, Concrete, Asbestos sheets.",
    "method_of_application": "2 coats putty, 1 coat primer, 2-3 coats paints",
    "primer": "Premium Exterior – Interior primer", 
    "coverage": "130/140 sq. ft. per Litre per coat",
    "finish": "Luxurious  Glossy  Finish",
    "packing_available": "1lit , 4lit, 10lit , 20lit",
    "images": "img/primer.jpg"
  },
  {
    "name": "Diamond Coat  Lustre ",
    "raw_snippet": "Diamond coat lustre is a premium emulsion paint   made of top quality acrylic polymers  that  providers a  luxurious  finis h & silk appearance to your Walls.a)  Low VOC  & odourless   -  5 Years performance .b)  Good  wash ability   -  Anti bacterial",
    "area_of_application": "Plaster, Fall ceiling, Concrete, Asbestos sheets.",
    "method_of_application": "2coats putty, 1 coat primer , 2-3 coats paints",
    "coverage": "130/140 sq. ft. per Litre per coat ",
    "finish": "Luxurious Silk finish",
    "packing_available": "1lit, 4 lit, 10lit ,20lit",
    "images": "img/IMG-20250915-WA0029.jpg"
  },
  {
    "name": "Phinix  Gold Premium Dust Proof Ext Emulsion",
    "raw_snippet": "Phinix Gold Premium Dust Ext Emulsion is a high performance coating for exterior  walls . It is  based  on pure acrylic emulsion which gives tough adhesion , flexibility & controls fungal & algae growth.",
    "area_of_application": " Plaster, Concrete , Asbestos sheets.",
    "precaution":"Not recommended on lime wash",
    "method_of_application": "2 coat primer, 2-3 coats paints",
    "primer":"Premium Exterior  primer",
    "thinning":"30 40% by volume",
    "coverage": "130/140 sq. ft. per Litre per coat",
    "finish": "Rich finish with sheen",
    "packing_available": "1lit , 4 lit, 10 lit , 20lit.",
    "images": "img/IMG-20250915-WA0028.jpg"
  },
  {
    "name": "Diamond  Coat  Premium Ext Emulsion",
    "raw_snippet": " Diamond Coat Premium Ext Emulsion is a high performance coating for exterior  walls . It is   based  on pure acrylic emulsion which gives tough adhesion , bright finish good  flexibility , controls fungal & algae growth.",
    "area_of_application": "Plaster, Concrete , Asbestos sheets.",
    "precaution":"Not recommended on lime wash",
    "method_of_application": " 2 coats primer, 2-3 coats paints",
    "primer":"Premium Exterior  primer",
    "thinning":"30 40% by volume",
    "coverage": "130/140 sq. ft. per Litre per coat",
    "finish": "Rich finish with sheen",
    "packing_available": "1lit , 4 lit, 10 lit , 20lit.",
    "images": "img/IMG-20250915-WA0028.jpg"
  },
  {
    "name": "Phinix Ready Dark Shades Emulsion",
    "raw_snippet": "Phinix  Ready Dark Shade Emulsion is a high performance coating for exterior walls. Available in dark shades .",
    "area_of_application": "Plaster, Concrete, Asbestos sheets.",
    "precaution":"Not recommended on lime wash",
    "method_of_application": " 2 coats primer, 2-3 coats paints",
    "primer":"Premium Exterior – Interior primer ",
    "thinning":"20 - 30% by volume",
    "coverage": "130/140 sq. ft. per Litre per coat",
    "finish": "Rich Matt  finish",
    "packing_available": "1lit , 4 lit, 10 lit , 20lit.",
    "images": "img/IMG-20250915-WA0028.jpg"
  },
  {
    "name": "Phinix Silver Ext Emulsion ( SB2 )",
    "raw_snippet": " Phinix Silver Ext Emulsion is made from acrylic co- polymer  emulsion. It's formula ensure that the product has excellent types of bright surface.",
    "area_of_application": "Plaster, Concrete , Asbestos sheets.",
    "precaution":"Not recommended on lime wash",
    "method_of_application": " 2 coats primer, 2-3 coats paints",
    "primer":" Premium Exterior – Interior primer",
    "thinning":"40 - 50% by volume",
    "coverage": "130/140 sq. ft. per Litre per coat",
    "finish": "smooth  Matt  finish ",
    "packing_available": "1lit , 4 lit, 10 lit , 20lit.",
    "images": "img/IMG-20250915-WA0028.jpg"
  },
  {
    "name": " Diamond Coat Textures",
    "raw_snippet": "Is  made from high quality pure acrylic emulsion which retains the elegance & premium looks for various texture designs  for exterior interior walls. Fire resistance, Water repellent Up to 7 years  performance , also use for felling wall cracks.",
    "area_of_application": "Concrete , Exterior – Interior Plaster",
    "primer":"Premium  Exterior – Interior primer ",
    "thinning":"40 - 50% by volume",
    "coverage": "3-3,5 sq .ft. per Litre per coat",
    "finish": "Rich  Matt  finish",
    "packing_available": "1lit, 4 lit, 10 lit, 20 lit & 20lit poly bags",
    "images": "img/IMG-20250915-WA0023.jpg"
  },
  {
    "name": "Phinix  Metallic  Emulsion",
    "raw_snippet": "Premium   Metalic  Emulsion  is made from 100% acrylic emulsion which gives high performance glossy metallic finish  when applied on exterior & interior walls.",
    "area_of_application": "Plaster   Concrete , Asbestos sheets",
    "method of Application" : " can be applied by Brush , Roller",
    "primer":"Premium  Exterior – Interior primer ",
    "thinning":"20-30% by volume",
    "coverage": "80/90sq.ft. per Litre per coat",
    "finish": "Rich  Matt  finish",
    "packing_available": "1 lit, 4 lit , 10 lit , 20 lit , various shades",
    "images": "img/IMG-20250915-WA0028.jpg"
  },
  {
    "name": "Everest Cool Homes  ( Thanda  Ghar )",
    "raw_snippet": "Everest  Cool  Homes  is made from high quality pure acrylic  emulsion which keeps your interior temperature lower by up to 7/10 c. It reduces interior temperature  drastically & it resists ultra violet rays. Also use for plastic & cement plaster water tank   to keep Water normal temperature. ",
    "area_of_application": "Asbestos  sheets.",
    "thinning":"30 - 40% by potable water for 1st coat, 40% for 2nd coat",
    "coverage": "40 sq. ft. per kg per coat",
    "finish": "Super White matt finish ",
    "packing_available": " 5 kg , 10kg , 4lit , 10lit ,20lit",
    // 'extra_info':"Oil Base Product Range (Diamond Coat / Dixon) 1. Red oxide Matt / Glossy , Black Japan 2.  Universal white primer , Zinc Yellow Primer3. Black Board Paint 4. Aluminium Paint 5. Enamel  (Oil paints) - all shades 6.  Hammertone Finish & Furniture Enamel. 7. Pu . Polish for wood & stones .8. Industrial Paints – fast drying paints & Primers, Epoxy paints & primers",
    "images": "img/IMG-20250915-WA0025.jpg"
  },
  {
    "name": "Diamond Coat Acrylic Ready Shades Eco Distemper",
    "raw_snippet": "Diamond Coat Acrylic Ready Economic distemper which gives Smooth & Soft finish to your  walls. Which is available in all Light & Dark shades  for all festivals like  Ganesh  & Diwali.",
    "area_of_application": " Interior Plaster, Concrete, Asbestos sheets.",
    "method of Application" : "2 coats putty, 1 coat primer, 2-3 coats paints",
    "primer":"Premium  Exterior – Interior primer ",
    "thinning":"20-30% by volume",
    "coverage": "40/50 sq. ft. per kg per coat",
    "finish": "Bright  Matt finish",
    "packing_available": "1kg  ( 1kg  x  20 Nos Box )",
    "images": "img/IMG-20250915-WA0017.jpg"
  },
  {
    "name": "Diamond Coat Water Proof Cement Paint",
    "raw_snippet": "This cement paint (powder  base) is use for exterior walls which gives premium bright finish ",
    "area_of_application": "Plaster, Concrete , Asbestos sheets.",
    "method of Application" : " 2 coats paints ",
    "thinning":"first 5% -10% by volume for slurry put for 10mints then dilute  by  10% - 20%   by volume",   
    "coverage": " 800/1000 sq. ft. Per 25 kg  per coat",
    "finish": " smooth  Matt  finish ",
    "packing_available": " 5 kg , 25 kg",
    "images": "img/IMG-20250915-WA0024.jpg"
  },
  {
    "name": "Diamond Coat Interior Emulsion",
    "raw_snippet": "Diamond Interior Emulsion  is a acrylic  Emulsion paint which gives Smooth  & Soft finish to your  walls. It gives 50% more coverage than distempers.",
    "area_of_application": "Plaster ,  Concrete , Asbestos sheets.",
    "method of Application" : " 2 coats putty, 1 coat primer, 2-3 coats paints",
    "primer":"Premium Interior primer",
    "coverage": " 110/120 sq. ft. per Litre per coat ",
    "finish": "Silky Matt finish",
    "packing_available": " 1 lit , 4lit , 10 lit, 20 lit",
    "images": "img/IMG-20250915-WA0029.jpg"
  },
  {
    "name": "Real Star Acrylic Premium Distemper",
    "raw_snippet": "Real Star Acrylic distemper  is premium distemper  which gives Smooth  & Soft finish to your  walls..Low VCO & odourless",
    "area_of_application": "Plaster ,  Concrete , Asbestos sheets.",
    "method of Application" : "2 coats putty, 1 coat primer, 2-3 coats paints",
    "primer":"Premium Interior primer",
    "coverage": "50/60 sq. ft. per kg per coat ",
    "finish": "Silky Matt finish",
    "packing_available": " 1 kg , 5kg , 10kg, 20kg",
    "images": "img/IMG-20250915-WA0031.jpg"
  },
  {
    "name": "Diamond Coat Premium Glossy Ext / Int Emulsion",
    "raw_snippet": " Diamond  Coat Premium Glossy Ext / Int emulsion paint made of top quality pure acrylic emulsion that providers a satin & silky appearance to your walls.* Low VCO & odourless * 3 years performance * Good Stain resistance.",
    "area_of_application": "Plaster, Fall ceilings, Concrete, Asbestos sheets.",
    "method of Application" : "1 coats primer,2 coat putty, 2-3 coats paints ",
    "primer":"Premium Interior/ exterior primer ",
    "coverage": " 110/120 sq. ft. per Litre per coat",
    "finish": "Luxurious semi glossy finish",
    "packing_available": " 1 lit , 4lit , 10 lit, 20 lit",
    "images": "img/IMG-20250915-WA0029.jpg"
  },
  {
    "name": "Diamond Coat Acrylic Eco Distemper",
    "raw_snippet": "Diamond Coat Acrylic Eco distemper  which gives Smooth  & Soft finish to your  walls..",
    "area_of_application": " Plaster ,  Concrete , Asbestos sheets.",
    "method of Application" : "2 coats putty, 1 coat primer, 2 coats paints",
    "coverage": " 40/50 sq. ft. per kg per coat",
    "finish": "Bright  Matt finish",
    "packing_available": "1kg, 5 kg, 10kg, 20kg",
    "images": "img/IMG-20250915-WA0022.jpg"
  },
  {
    "name": "Dixon Exterior / Interior Primer ",
    "raw_snippet": "Dixon Exterior/ Interior wall primer, is economy primer used for distemper & emulsion.",
    "area_of_application": "Palster , Concrete, Asbestos sheets",
    "method of Application" : "can be applied br Brush or Roller",
    "coverage": " 90 / 100 sq.ft.per Litre per coat",
    "thinning": "40 % by volume.",
    "finish": "Bright  Matt finish",
    "packing_available": " 1 lit, 4 lit, 10 lit, 20lit.",
    // "extra_info":"Everest Cool Homes is made from high quality acrylic emulsion which keeps your interior temperature lower by up to 09'c It reduces interior temperature drastically.",
    "images": "img/IMG-20250915-WA0018.jpg"
  }
]
